name: tmdb_dart
version: 0.1.1
description: >-
  Type Safe API client for The Movie Database API (v3)[https://developers.themoviedb.org/3/]
environment:
  sdk: '>=2.1.0 <3.0.0'
authors:
  - Marian Bejenari <kerego@outlook.com>
  - Akash Mondal <a98mondal@gmail.com>
homepage: https://github.com/Kerego/tmdb_dart
dependencies:
  http: ^0.12.0+4
